database1:
  datasource:
    driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
    url: "jdbc:sqlserver://localhost;databaseName=db_cbo"
    username: "sa"
    password: "Dinesh87?"
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  secondDatasource:
    url : ""
    username : [username]
    password : [password]
    driverClassName : "oracle.jdbc.OracleDriver"

server:
  port:80

logging:
  level:
    org:
      springframework:
        web: debug

      hibernate: ERROR
  file:
    name: "ganesh.log"

